CREATE USER IF NOT EXISTS "CSID" SALT '8e986f34ffbfb3ce' HASH 'b0e9542f673d20a95824923df7a1ad5c29d9764dd09bf71b4b7684fe00561acc' ADMIN;
CREATE MEMORY TABLE "PUBLIC"."AUTHORITIES"(
    "USERNAME" VARCHAR(255) NOT NULL,
    "AUTHORITY" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."AUTHORITIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("USERNAME");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.AUTHORITIES;
CREATE MEMORY TABLE "PUBLIC"."COMPANY"(
    "ID" VARCHAR(255) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "NAME" VARCHAR(255),
    "USER_ENTITY_USERNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."COMPANY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMPANY;
CREATE MEMORY TABLE "PUBLIC"."FILE"(
    "ID" VARCHAR(255) NOT NULL,
    "ADDED_DATE" TIMESTAMP,
    "COMPANY" VARCHAR(255),
    "DOCUMENT_DATE" TIMESTAMP,
    "DOCUMENT_TYPE" VARCHAR(255),
    "GROSS_SALARY" DOUBLE,
    "MODIFIED_DATE" TIMESTAMP,
    "NAME" VARCHAR(255),
    "NET_SALARY" DOUBLE,
    "SIZE" BIGINT,
    "TYPE" VARCHAR(255),
    "WORKPLACE" VARCHAR(255),
    "FILE_CONTENT_ID" VARCHAR(255),
    "FOLDER_ID" VARCHAR(255),
    "USER_ENTITY_USERNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."FILE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.FILE;
CREATE MEMORY TABLE "PUBLIC"."FILE_CONTENT"(
    "ID" VARCHAR(255) NOT NULL,
    "FILE_CONTENT" BLOB
);
ALTER TABLE "PUBLIC"."FILE_CONTENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.FILE_CONTENT;
CREATE MEMORY TABLE "PUBLIC"."FOLDER"(
    "ID" VARCHAR(255) NOT NULL,
    "NAME" VARCHAR(255),
    "PARENT_FOLDER_ID" VARCHAR(255),
    "USER_ENTITY_USERNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."FOLDER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.FOLDER;
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "USERNAME" VARCHAR(255) NOT NULL,
    "ENABLED" VARCHAR(255),
    "PASSWORD" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("USERNAME");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;
CREATE MEMORY TABLE "PUBLIC"."WORKPLACE"(
    "ID" VARCHAR(255) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "NAME" VARCHAR(255),
    "COMPANY_ENTITY_ID" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."WORKPLACE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WORKPLACE;
ALTER TABLE "PUBLIC"."FILE" ADD CONSTRAINT "PUBLIC"."FKBPBUCNI21HACFO7JQU5VFBT27" FOREIGN KEY("FILE_CONTENT_ID") REFERENCES "PUBLIC"."FILE_CONTENT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."FILE" ADD CONSTRAINT "PUBLIC"."FKTFYSDFLDYP5UWN5ESWB6TRJT0" FOREIGN KEY("USER_ENTITY_USERNAME") REFERENCES "PUBLIC"."USERS"("USERNAME") NOCHECK;
ALTER TABLE "PUBLIC"."FOLDER" ADD CONSTRAINT "PUBLIC"."FK57G7VEIS1GP5WN3G0MP0X57PL" FOREIGN KEY("PARENT_FOLDER_ID") REFERENCES "PUBLIC"."FOLDER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."FOLDER" ADD CONSTRAINT "PUBLIC"."FKF9MQIURCHDHX9TD5WAMYFAEXR" FOREIGN KEY("USER_ENTITY_USERNAME") REFERENCES "PUBLIC"."USERS"("USERNAME") NOCHECK;
ALTER TABLE "PUBLIC"."WORKPLACE" ADD CONSTRAINT "PUBLIC"."FKFFRJSJEN6GW9JCBLCR1VEEXMM" FOREIGN KEY("COMPANY_ENTITY_ID") REFERENCES "PUBLIC"."COMPANY"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."COMPANY" ADD CONSTRAINT "PUBLIC"."FK1CSVDY8LBBNOGSIH6WL6KHT3K" FOREIGN KEY("USER_ENTITY_USERNAME") REFERENCES "PUBLIC"."USERS"("USERNAME") NOCHECK;
ALTER TABLE "PUBLIC"."FILE" ADD CONSTRAINT "PUBLIC"."FKDFGD9QOVCGEBJRY9MYNTTNIJC" FOREIGN KEY("FOLDER_ID") REFERENCES "PUBLIC"."FOLDER"("ID") NOCHECK;